### PR TITLE
switch markdownlint container to markdownlint-cli2

### PR DESCRIPTION
**Pull request by tuminoid**
Switch markdownlint container to markdownlint-cli2.

- project-infra PR https://github.com/metal3-io/project-infra/pull/619 needs to merge for markdownlint here to pass

### CODE REVIEW

**Comment by tuminoid** [comment]
/hold
Needs project-infra PR to land first.

**Review by lentzi90 — COMMENTED** [review]
/lgtm

**Review by lentzi90 — DISMISSED** [review]

**Review by lentzi90 — APPROVED** [review]
/lgtm

**Comment by tuminoid** [comment]
Bumped to 0.9.0 release of the image from 2 days ago.

**Review by smoshiur1237 — COMMENTED** [review]
/approve

**Review by smoshiur1237 — APPROVED** [review]

**Comment by tuminoid** [comment]
/retest
Test new linter.

**Comment by tuminoid** [comment]
/unhold
Good to go.

**Pull request merged**
