### PR TITLE
bump markdownlint to 0.13.0

### PR DESCRIPTION
**Pull request by tuminoid**
Bump markdownlint to 0.13.0

TODO: bump the image in project-infra when all bump PRs are merged.

### CODE REVIEW

**Comment by kashifest** [comment]
Trying my luck 
/approve

**Review by smoshiur1237 — APPROVED** [review]
/lgtm

**Comment by tuminoid** [comment]
Seems were missing OWNERS file here. @Rozzii

**Comment by tuminoid** [comment]
/hold
Until OWNERS file exists.

**Review by smoshiur1237 — APPROVED** [review]
/lgtm

**Comment by tuminoid** [comment]
/unhold
We have OWNERS now.
/assign @Rozzii

**Review by Rozzii — APPROVED** [review]
/approve

**Comment by tuminoid** [comment]
> /cherry-pick sles-15-sp4

Is cherry-pick bot not enabled for this repo? Doing it manually then...

**Pull request merged**
